#!/usr/bin/env python3
"""Generate one wiki page per action, from the OpenAPI spec.

There are fourteen actions, each with a tool and an endpoint, and a page that
described them by hand would be wrong within a month. The spec is already
generated from the live MCP tool schemas and a test fails when it goes stale, so
it is the one description of the surface that cannot drift — these pages are
rendered from it for the same reason.

The spec is built in-process rather than read off disk. ``openapi.yaml`` is a
generated artifact and is not committed, so depending on the file would mean
this script could only run after another one had written it — and could render
a wiki from a stale copy if it had not.

What is NOT generated is the prose: every page ends by including a hand-written
fragment from ``wiki/notes/<tool>.notes.md`` when one exists, so guidance a
schema cannot express has somewhere to live that regeneration will not flatten.

    python scripts/generate_wiki.py            # write the pages
    python scripts/generate_wiki.py --check    # fail if they are out of date
"""

from __future__ import annotations

import argparse
import asyncio
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from kubed.selenium_flow.openapi import build_spec
from kubed.selenium_flow.routes import ENDPOINTS
from kubed.selenium_flow.server import SeleniumMCP

WIKI = REPO / "wiki"
NOTES = WIKI / "notes"
# `<tool>.notes.md`, not `<tool>.md`, and the suffix is load-bearing. A GitHub
# wiki addresses a page by BASENAME whatever directory it sits in, so a note
# named for its tool would answer to the same URL as the page it belongs to —
# and GitHub served the fragment, leaving the page looking like it had lost
# everything but its prose while the file on disk was perfect. The suffix is
# what keeps the two apart; test_no_page_is_shadowed_by_a_file_in_a_subdirectory
# fails if it is ever dropped.
NOTES_SUFFIX = ".notes.md"

BANNER = (
    "<!-- Generated by scripts/generate_wiki.py from the OpenAPI spec. Do not edit:\n"
    "     prose belongs in wiki/notes/{name}.notes.md, which is included below. -->"
)

# The one place the two surfaces are named together, in the order a reader meets
# them: open a browser, do something, read the result, put it back.
ORDER = [
    "open_session",
    "navigate",
    "interact",
    "write",
    "press_key",
    "extract",
    "screenshot",
    "save_pdf",
    "execute_script",
    "frame",
    "dialog",
    "resize",
    "upload_file",
    "close_session",
]


async def _build() -> dict:
    # A token so the security scheme is described; the address is never dialled.
    server = SeleniumMCP(grid_url="http://grid.invalid:4444", auth_token="generated")
    return await build_spec(server.mcp, ENDPOINTS, "/browser", authenticated=True)


def load() -> dict:
    """The spec, straight from the live tool schemas."""
    return asyncio.run(_build())


def resolve(spec: dict, node: dict) -> dict:
    """Follow a local $ref, once — the spec never nests them deeper."""
    ref = node.get("$ref")
    if not ref:
        return node
    return spec["components"]["schemas"][ref.rsplit("/", 1)[-1]]


def type_of(field: dict) -> str:
    """A field's type, with the null branch read as optionality instead.

    ``anyOf: [string, null]`` is how an optional argument arrives from the tool
    schema, and printing it verbatim would tell a reader about JSON Schema
    rather than about the parameter.
    """
    branches = field.get("anyOf")
    if branches:
        names = [b.get("type") for b in branches if b.get("type") != "null"]
        return " or ".join(n for n in names if n) or "any"
    if "type" in field:
        return field["type"]
    return "any"


def default_of(field: dict) -> str:
    if "default" not in field or field["default"] is None:
        return "—"
    value = field["default"]
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def clean(text: str | None) -> str:
    """Collapse a docstring's hard wrapping into flowing markdown."""
    if not text:
        return ""
    out = []
    for block in text.split("\n\n"):
        stripped = block.strip("\n")
        # A code block or a list keeps its line breaks; prose does not.
        if stripped.lstrip().startswith(("- ", "* ", "|", "```", "    ")):
            out.append(stripped)
        else:
            out.append(" ".join(line.strip() for line in stripped.splitlines()))
    return "\n\n".join(b for b in out if b)


def table(rows: list[list[str]], head: list[str]) -> str:
    lines = ["| " + " | ".join(head) + " |", "|" + "|".join(["---"] * len(head)) + "|"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


def parameters(spec: dict, schema: dict) -> str:
    props = schema.get("properties") or {}
    if not props:
        return "_This action takes no parameters._"
    required = set(schema.get("required") or [])
    rows = []
    for name, field in props.items():
        note = clean(field.get("description")) or ""
        mark = "**yes**" if name in required else "no"
        # session_id is the one parameter whose requirement depends on the
        # caller, so the table says so rather than picking one answer.
        if name == "session_id":
            mark = "**yes** over HTTP"
            note = note or "Omit over MCP when the server is holding your browser."
        rows.append([f"`{name}`", type_of(field), mark, default_of(field), note])
    # Argument descriptions come from Python signatures, which have none, so the
    # column is usually empty. An empty column is worse than no column.
    if not any(row[-1] for row in rows):
        return table(
            [row[:-1] for row in rows], ["Name", "Type", "Required", "Default"]
        )
    return table(rows, ["Name", "Type", "Required", "Default", "Notes"])


def returns(spec: dict, schema: dict) -> str:
    props = schema.get("properties") or {}
    if not props:
        return "_An object._"
    rows = [
        [f"`{name}`", type_of(field), clean(field.get("description")) or ""]
        for name, field in props.items()
    ]
    return table(rows, ["Field", "Type", "Notes"])


def example(tool: str, path: str, schema: dict) -> str:
    """A call in both shapes, using only the parameters that are required."""
    required = [n for n in (schema.get("required") or []) if n != "session_id"]
    props = schema.get("properties") or {}
    sample = {}
    for name in required:
        kind = type_of(props.get(name, {}))
        sample[name] = {"string": "…", "integer": 0, "boolean": True}.get(kind, "…")
    mcp_args = ", ".join(
        f'{k}="{v}"' if isinstance(v, str) else f"{k}={v}" for k, v in sample.items()
    )
    body = {"session_id": "…", **sample}
    payload = ",\n    ".join(
        f'"{k}": {"null" if v is None else repr(v)}' for k, v in body.items()
    ).replace("'", '"')
    return (
        f"**MCP**\n\n```\n{tool}({mcp_args})\n```\n\n"
        f"**HTTP**\n\n```bash\ncurl -X POST $SELENIUM_FLOW/browser/{path} \\\n"
        f'  -H "Authorization: Bearer $TOKEN" \\\n'
        f"  -H 'Content-Type: application/json' \\\n"
        f"  -d '{{\n    {payload}\n  }}'\n```"
    )


def render(spec: dict, tool: str, path: str, op: dict) -> str:
    request = resolve(spec, op["requestBody"]["content"]["application/json"]["schema"])
    response = resolve(
        spec, op["responses"]["200"]["content"]["application/json"]["schema"]
    )
    description = clean(op.get("description"))
    summary = clean(op.get("summary"))
    # The summary is the description's first line, so printing both repeats it.
    if description.startswith(summary):
        description = description[len(summary) :].strip()

    note = NOTES / f"{tool}{NOTES_SUFFIX}"
    extra = f"\n\n{note.read_text().strip()}\n" if note.is_file() else ""

    return f"""{BANNER.format(name=tool)}

# `{tool}`

> {summary}

|  |  |
|---|---|
| **MCP tool** | `{tool}` |
| **HTTP** | `POST /browser/{path}` |

{description}

## Parameters

{parameters(spec, request)}

## Returns

{returns(spec, response)}

Errors are `400` for a bad argument, `401` without a token, `500` when the Grid
refuses. Over MCP the same failures arrive as a tool error.

## Example

{example(tool, path, request)}
{extra}
---

[← All actions](Actions) · [Installing](Installing) · [Deployment](Deployment)
"""


def pages(spec: dict) -> dict[str, str]:
    by_tool = {}
    for path, item in spec["paths"].items():
        op = item.get("post")
        if not op or not path.startswith("/browser/"):
            continue
        tool = op["operationId"]
        by_tool[tool] = (path.removeprefix("/browser/"), op)

    missing = set(by_tool) - set(ORDER)
    if missing:
        raise SystemExit(
            f"add these to ORDER in {__file__}: {', '.join(sorted(missing))}"
        )

    out = {}
    for tool in ORDER:
        if tool not in by_tool:
            continue
        endpoint, op = by_tool[tool]
        out[f"{tool}.md"] = render(spec, tool, endpoint, op)

    rows = [
        [
            f"[`{tool}`]({tool})",
            f"`POST /browser/{by_tool[tool][0]}`",
            clean(by_tool[tool][1].get("summary")),
        ]
        for tool in ORDER
        if tool in by_tool
    ]
    out["Actions.md"] = f"""{BANNER.format(name="Actions")}

# Actions

Every action is an MCP tool **and** an HTTP endpoint with the same parameters. A
test fails the build if one exists without the other.

{table(rows, ["Tool", "Endpoint", "Does"])}

Over HTTP `session_id` is always required. Over MCP it depends on whether the
server can identify you — see [Sessions](Sessions).

---

[Installing](Installing) · [Deployment](Deployment) · [Administration](Administration)
"""
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if stale")
    args = parser.parse_args()

    if not WIKI.is_dir():
        raise SystemExit("wiki/ is not checked out — run: git submodule update --init")

    rendered = pages(load())
    stale = []
    for name, body in rendered.items():
        target = WIKI / name
        if not target.is_file() or target.read_text() != body:
            stale.append(name)
        if not args.check:
            target.write_text(body)

    if args.check:
        if stale:
            print("stale wiki pages: " + ", ".join(stale), file=sys.stderr)
            print("run python scripts/generate_wiki.py", file=sys.stderr)
            return 1
        print(f"{len(rendered)} wiki pages up to date")
        return 0

    print(f"wrote {len(rendered)} pages to {WIKI}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
